export const activitiesConstants = {
  ACTIVITIES_ADD: 'ACTIVITIES_ADD',
  ACTIVITIES_FETCHING_ADD: 'ACTIVITIES_FETCHING_ADD',
  ACTIVITIES_SUCCESS_ADDED: 'ACTIVITIES_SUCCESS_ADDED',

  ACTIVITIES_LIST_ACTIVITIES: 'ACTIVITIES_LIST_ACTIVITIES',
  ACTIVITIES_FETCHING_LIST_ACTIVITIES: 'ACTIVITIES_FETCHING_LIST_ACTIVITIES',

  ACTIVITIES_GET_ID: 'ACTIVITIES_GET_ID',
  ACTIVITIES_FETCHING_GET_ID: 'ACTIVITIES_FETCHING_GET_ID',

  ACTIVITIES_UPDATE_ID: 'ACTIVITIES_UPDATE_ID',
  ACTIVITIES_FETCHING_UPDATE_ID: 'ACTIVITIES_FETCHING_UPDATE_ID',

  ACTIVITIES_DELETE_ID: 'ACTIVITIES_DELETE_ID',
  ACTIVITIES_FETCHING_DELETE_ID: 'ACTIVITIES_FETCHING_DELETE_ID',

  ACTIVITIES_SET_SUCCESS: 'ACTIVITIES_SET_SUCCESS',
  ACTIVITIES_SET_FIELD_SUCCESS: 'ACTIVITIES_SET_FIELD_SUCCESS',

  ACTIVITIES_ERROR_MESSAGE: 'ACTIVITIES_ERROR_MESSAGE',
  ACTIVITIES_SUCCESS_MESSAGE: 'ACTIVITIES_SUCCESS_MESSAGE',

  ACTIVITIES_RESET: 'ACTIVITIES_RESET'
};