export const clientPlacesConstants = {
  CLIENT_PLACES_ADD: 'CLIENT_PLACES_ADD',
  CLIENT_PLACES_FETCHING_ADD: 'CLIENT_PLACES_FETCHING_ADD',
  CLIENT_PLACES_SUCCESS_ADDED: 'CLIENT_PLACES_SUCCESS_ADDED',

  CLIENT_PLACES_LIST_PLACES: 'CLIENT_PLACES_LIST_PLACES',
  CLIENT_PLACES_FETCHING_LIST_PLACES: 'CLIENT_PLACES_FETCHING_LIST_PLACES',

  CLIENT_PLACES_GET_ID: 'CLIENT_PLACES_GET_ID',
  CLIENT_PLACES_FETCHING_GET_ID: 'CLIENT_PLACES_FETCHING_GET_ID',

  CLIENT_PLACES_UPDATE_ID: 'CLIENT_PLACES_UPDATE_ID',
  CLIENT_PLACES_FETCHING_UPDATE_ID: 'CLIENT_PLACES_FETCHING_UPDATE_ID',

  CLIENT_PLACES_DELETE_ID: 'CLIENT_PLACES_DELETE_ID',
  CLIENT_PLACES_FETCHING_DELETE_ID: 'CLIENT_PLACES_FETCHING_DELETE_ID',

  CLIENT_PLACES_SET_SUCCESS: 'CLIENT_PLACES_SET_SUCCESS',
  CLIENT_PLACES_SET_FIELD_SUCCESS: 'CLIENT_PLACES_SET_FIELD_SUCCESS',

  CLIENT_PLACES_ERROR_MESSAGE: 'CLIENT_PLACES_ERROR_MESSAGE',
  CLIENT_PLACES_SUCCESS_MESSAGE: 'CLIENT_PLACES_SUCCESS_MESSAGE',

  CLIENT_PLACES_RESET: 'CLIENT_PLACES_RESET'
};