export const clientsConstants = {
  CLIENT_ADD: 'CLIENT_ADD',
  CLIENT_FETCHING_ADD: 'CLIENT_FETCHING_ADD',
  CLIENT_SUCCESS_ADDED: 'CLIENT_SUCCESS_ADDED',

  CLIENT_LIST_CLIENTS: 'CLIENT_LIST_CLIENTS',
  CLIENT_FETCHING_LIST_CLIENTS: 'CLIENT_FETCHING_LIST_CLIENTS',

  CLIENT_GET_ID: 'CLIENT_GET_ID',
  CLIENT_FETCHING_GET_ID: 'CLIENT_FETCHING_GET_ID',

  CLIENT_UPDATE_ID: 'CLIENT_UPDATE_ID',
  CLIENT_FETCHING_UPDATE_ID: 'CLIENT_FETCHING_UPDATE_ID',

  CLIENT_DELETE_ID: 'CLIENT_DELETE_ID',
  CLIENT_FETCHING_DELETE_ID: 'CLIENT_FETCHING_DELETE_ID',

  CLIENT_SET_SUCCESS: 'CLIENT_SET_SUCCESS',
  CLIENT_SET_FIELD_SUCCESS: 'CLIENT_SET_FIELD_SUCCESS',

  CLIENT_ERROR_MESSAGE: 'CLIENT_ERROR_MESSAGE',
  CLIENT_SUCCESS_MESSAGE: 'CLIENT_SUCCESS_MESSAGE',

  CLIENT_RESET: 'CLIENT_RESET'
};