export const driverConstants = {
  DRIVER_ADD: 'DRIVER_ADD',
  DRIVER_FETCHING_ADD: 'DRIVER_FETCHING_ADD',
  DRIVER_SUCCESS_ADDED: 'DRIVER_SUCCESS_ADDED',

  DRIVER_LIST_DRIVERS: 'DRIVER_LIST_DRIVERS',
  DRIVER_FETCHING_LIST_DRIVERS: 'DRIVER_FETCHING_LIST_DRIVERS',

  DRIVER_GET_ID: 'DRIVER_GET_ID',
  DRIVER_FETCHING_GET_ID: 'DRIVER_FETCHING_GET_ID',

  DRIVER_UPDATE_ID: 'DRIVER_UPDATE_ID',
  DRIVER_FETCHING_UPDATE_ID: 'DRIVER_FETCHING_UPDATE_ID',

  DRIVER_DELETE_ID: 'DRIVER_DELETE_ID',
  DRIVER_FETCHING_DELETE_ID: 'DRIVER_FETCHING_DELETE_ID',

  DRIVER_SET_SUCCESS: 'DRIVER_SET_SUCCESS',
  DRIVER_SET_FIELD_SUCCESS: 'DRIVER_SET_FIELD_SUCCESS',

  DRIVER_ERROR_MESSAGE: 'DRIVER_ERROR_MESSAGE',
  DRIVER_SUCCESS_MESSAGE: 'DRIVER_SUCCESS_MESSAGE',

  DRIVER_RESET: 'DRIVER_RESET'
};