export const facilitiesConstants = {
  FACILITIES_ADD: 'FACILITIES_ADD',
  FACILITIES_FETCHING_ADD: 'FACILITIES_FETCHING_ADD',
  FACILITIES_SUCCESS_ADDED: 'FACILITIES_SUCCESS_ADDED',

  FACILITIES_LIST_FACILITIES: 'FACILITIES_LIST_FACILITIES',
  FACILITIES_FETCHING_LIST_FACILITIES: 'FACILITIES_FETCHING_LIST_FACILITIES',

  FACILITIES_GET_ID: 'FACILITIES_GET_ID',
  FACILITIES_FETCHING_GET_ID: 'FACILITIES_FETCHING_GET_ID',

  FACILITIES_UPDATE_ID: 'FACILITIES_UPDATE_ID',
  FACILITIES_FETCHING_UPDATE_ID: 'FACILITIES_FETCHING_UPDATE_ID',

  FACILITIES_DELETE_ID: 'FACILITIES_DELETE_ID',
  FACILITIES_FETCHING_DELETE_ID: 'FACILITIES_FETCHING_DELETE_ID',

  FACILITIES_SET_SUCCESS: 'FACILITIES_SET_SUCCESS',
  FACILITIES_SET_FIELD_SUCCESS: 'FACILITIES_SET_FIELD_SUCCESS',

  FACILITIES_ERROR_MESSAGE: 'FACILITIES_ERROR_MESSAGE',
  FACILITIES_SUCCESS_MESSAGE: 'FACILITIES_SUCCESS_MESSAGE',

  FACILITIES_RESET: 'FACILITIES_RESET'
};