export const programsConstants = {
  PROGRAMS_ADD: 'PROGRAMS_ADD',
  PROGRAMS_FETCHING_ADD: 'PROGRAMS_FETCHING_ADD',
  PROGRAMS_SUCCESS_ADDED: 'PROGRAMS_SUCCESS_ADDED',

  PROGRAMS_LIST_PROGRAMS: 'PROGRAMS_LIST_PROGRAMS',
  PROGRAMS_FETCHING_LIST_PROGRAMS: 'PROGRAMS_FETCHING_LIST_PROGRAMS',

  PROGRAMS_GET_ID: 'PROGRAMS_GET_ID',
  PROGRAMS_FETCHING_GET_ID: 'PROGRAMS_FETCHING_GET_ID',

  PROGRAMS_UPDATE_ID: 'PROGRAMS_UPDATE_ID',
  PROGRAMS_FETCHING_UPDATE_ID: 'PROGRAMS_FETCHING_UPDATE_ID',

  PROGRAMS_DELETE_ID: 'PROGRAMS_DELETE_ID',
  PROGRAMS_FETCHING_DELETE_ID: 'PROGRAMS_FETCHING_DELETE_ID',

  PROGRAMS_SET_SUCCESS: 'PROGRAMS_SET_SUCCESS',
  PROGRAMS_SET_FIELD_SUCCESS: 'PROGRAMS_SET_FIELD_SUCCESS',

  PROGRAMS_ERROR_MESSAGE: 'PROGRAMS_ERROR_MESSAGE',
  PROGRAMS_SUCCESS_MESSAGE: 'PROGRAMS_SUCCESS_MESSAGE',

  PROGRAMS_RESET: 'PROGRAMS_RESET'
};