export const programmedConstants = {
  PROGRAMMED_ADD: 'PROGRAMMED_ADD',
  PROGRAMMED_FETCHING_ADD: 'PROGRAMMED_FETCHING_ADD',
  PROGRAMMED_SUCCESS_ADDED: 'PROGRAMMED_SUCCESS_ADDED',

  PROGRAMMED_LIST_PROGRAMMED: 'PROGRAMMED_LIST_PROGRAMMED',
  PROGRAMMED_FETCHING_LIST_PROGRAMMED: 'PROGRAMMED_FETCHING_LIST_PROGRAMMED',

  PROGRAMMED_GET_ID: 'PROGRAMMED_GET_ID',
  PROGRAMMED_FETCHING_GET_ID: 'PROGRAMMED_FETCHING_GET_ID',

  PROGRAMMED_UPDATE_ID: 'PROGRAMMED_UPDATE_ID',
  PROGRAMMED_FETCHING_UPDATE_ID: 'PROGRAMMED_FETCHING_UPDATE_ID',

  PROGRAMMED_DELETE_ID: 'PROGRAMMED_DELETE_ID',
  PROGRAMMED_FETCHING_DELETE_ID: 'PROGRAMMED_FETCHING_DELETE_ID',

  PROGRAMMED_SET_SUCCESS: 'PROGRAMMED_SET_SUCCESS',
  PROGRAMMED_SET_FIELD_SUCCESS: 'PROGRAMMED_SET_FIELD_SUCCESS',

  PROGRAMMED_ERROR_MESSAGE: 'PROGRAMMED_ERROR_MESSAGE',
  PROGRAMMED_SUCCESS_MESSAGE: 'PROGRAMMED_SUCCESS_MESSAGE',

  PROGRAMMED_RESET: 'PROGRAMMED_RESET'
};