export const providerConstants = {
  PROVIDER_ADD: 'PROVIDER_ADD',
  PROVIDER_FETCHING_ADD: 'PROVIDER_FETCHING_ADD',
  PROVIDER_SUCCESS_ADDED: 'PROVIDER_SUCCESS_ADDED',

  PROVIDER_LIST_PROVIDERS: 'PROVIDER_LIST_PROVIDERS',
  PROVIDER_FETCHING_LIST_PROVIDERS: 'PROVIDER_FETCHING_LIST_PROVIDERS',

  PROVIDER_GET_ID: 'PROVIDER_GET_ID',
  PROVIDER_FETCHING_GET_ID: 'PROVIDER_FETCHING_GET_ID',

  PROVIDER_GET_PROVIDER_TYPES: 'PROVIDER_GET_PROVIDER_TYPES',
  PROVIDER_FETCHING_GET_PROVIDER_TYPES: 'PROVIDER_FETCHING_GET_PROVIDER_TYPES',

  PROVIDER_UPDATE_ID: 'PROVIDER_UPDATE_ID',
  PROVIDER_FETCHING_UPDATE_ID: 'PROVIDER_FETCHING_UPDATE_ID',

  PROVIDER_DELETE_ID: 'PROVIDER_DELETE_ID',
  PROVIDER_FETCHING_DELETE_ID: 'PROVIDER_FETCHING_DELETE_ID',

  PROVIDER_SET_SUCCESS: 'PROVIDER_SET_SUCCESS',
  PROVIDER_SET_FIELD_SUCCESS: 'PROVIDER_SET_FIELD_SUCCESS',

  PROVIDER_ERROR_MESSAGE: 'PROVIDER_ERROR_MESSAGE',
  PROVIDER_SUCCESS_MESSAGE: 'PROVIDER_SUCCESS_MESSAGE',

  PROVIDER_RESET: 'PROVIDER_RESET'
};