export const regionConstants = {
  REGION_ADD: 'REGION_ADD',
  REGION_FETCHING_ADD: 'REGION_FETCHING_ADD',
  REGION_SUCCESS_ADDED: 'REGION_SUCCESS_ADDED',

  REGION_LIST_REGIONS: 'REGION_LIST_REGIONS',
  REGION_FETCHING_LIST_REGIONS: 'REGION_FETCHING_LIST_REGIONS',

  REGION_GET_ID: 'REGION_GET_ID',
  REGION_FETCHING_GET_ID: 'REGION_FETCHING_GET_ID',

  REGION_UPDATE_ID: 'REGION_UPDATE_ID',
  REGION_FETCHING_UPDATE_ID: 'REGION_FETCHING_UPDATE_ID',

  REGION_DELETE_ID: 'REGION_DELETE_ID',
  REGION_FETCHING_DELETE_ID: 'REGION_FETCHING_DELETE_ID',

  REGION_SET_SUCCESS: 'REGION_SET_SUCCESS',
  REGION_SET_FIELD_SUCCESS: 'REGION_SET_FIELD_SUCCESS',

  REGION_ERROR_MESSAGE: 'REGION_ERROR_MESSAGE',
  REGION_SUCCESS_MESSAGE: 'REGION_SUCCESS_MESSAGE',

  REGION_RESET: 'REGION_RESET'
};