export const restrictedConstants = {
    RESTRICTED_ADD: 'RESTRICTED_ADD',
    RESTRICTED_FETCHING_ADD: 'RESTRICTED_FETCHING_ADD',
    RESTRICTED_SUCCESS_ADDED: 'RESTRICTED_SUCCESS_ADDED',

    RESTRICTED_LIST_AREAS: 'RESTRICTED_LIST_AREAS',
    RESTRICTED_FETCHING_LIST_AREAS: 'RESTRICTED_FETCHING_LIST_AREAS',

    RESTRICTED_GET_ID: 'RESTRICTED_GET_ID',
    RESTRICTED_FETCHING_GET_ID: 'RESTRICTED_FETCHING_GET_ID',

    RESTRICTED_UPDATE_ID: 'RESTRICTED_UPDATE_ID',
    RESTRICTED_FETCHING_UPDATE_ID: 'RESTRICTED_FETCHING_UPDATE_ID',

    RESTRICTED_DELETE_ID: 'RESTRICTED_DELETE_ID',
    RESTRICTED_FETCHING_DELETE_ID: 'RESTRICTED_FETCHING_DELETE_ID',

    RESTRICTED_SET_SUCCESS: 'RESTRICTED_SET_SUCCESS',
    RESTRICTED_SET_FIELD_SUCCESS: 'RESTRICTED_SET_FIELD_SUCCESS',

    RESTRICTED_ERROR_MESSAGE: 'RESTRICTED_ERROR_MESSAGE',
    RESTRICTED_SUCCESS_MESSAGE: 'RESTRICTED_SUCCESS_MESSAGE',

    RESTRICTED_RESET: 'RESTRICTED_RESET'
  };