export const routesConstants = {
  ROUTES_ADD: 'ROUTES_ADD',
  ROUTES_FETCHING_ADD: 'ROUTES_FETCHING_ADD',
  ROUTES_SUCCESS_ADDED: 'ROUTES_SUCCESS_ADDED',

  ROUTES_LIST_ACTIVITIES: 'ROUTES_LIST_ACTIVITIES',
  ROUTES_FETCHING_LIST_ROUTES: 'ROUTES_FETCHING_LIST_ROUTES',

  ROUTES_CHECKING_LIST_ROUTES: 'ROUTES_CHECKING_LIST_ROUTES',
  ROUTES_CHECK_LIST: 'ROUTES_CHECK_LIST',

  ROUTES_GET_ID: 'ROUTES_GET_ID',

  ROUTE_UPDATE_DRIVER: 'ROUTE_UPDATE_DRIVER',
  ROUTE_FETCHING_UPDATE_DRIVER: 'ROUTE_FETCHING_UPDATE_DRIVER',
  ROUTE_UPDATE_VEHICLE: 'ROUTE_UPDATE_VEHICLE',
  ROUTE_FETCHING_UPDATE_VEHICLE: 'ROUTE_FETCHING_UPDATE_VEHICLE',

  ROUTE_REMOVE_RIDER: 'ROUTE_REMOVE_RIDER',
  ROUTE_POSTING_REMOVE_RIDER: 'ROUTE_POSTING_REMOVE_RIDER',
  ROUTE_MOVE_POINT: 'ROUTE_MOVE_POINT',
  ROUTE_POSTING_MOVE_POINT: 'ROUTE_POSTING_MOVE_POINT',

  ROUTE_SET_SUCCESS: 'ROUTE_SET_SUCCESS',
  ROUTE_SET_FIELD_SUCCESS: 'ROUTE_SET_FIELD_SUCCESS',

  ROUTES_ERROR_MESSAGE: 'ROUTES_ERROR_MESSAGE',
  ROUTES_SUCCESS_MESSAGE: 'ROUTES_SUCCESS_MESSAGE',
  ROUTES_ERROR_LIST_MESSAGE: 'ROUTES_ERROR_LIST_MESSAGE',
  ROUTES_ERROR_GENERATE_MESSAGE: 'ROUTES_ERROR_GENERATE_MESSAGE',

  ROUTE_RESET: 'ROUTE_RESET'
};