export const schedulingConstants = {
  SCHEDULING_ADD: 'SCHEDULING_ADD',
  SCHEDULING_FETCHING_ADD: 'SCHEDULING_FETCHING_ADD',
  SCHEDULING_SUCCESS_ADDED: 'SCHEDULING_SUCCESS_ADDED',

  SCHEDULING_LIST_EVENTS: 'SCHEDULING_LIST_EVENTS',
  SCHEDULING_FETCHING_LIST_EVENTS: 'SCHEDULING_FETCHING_LIST_EVENTS',

  SCHEDULING_GET_ID: 'SCHEDULING_GET_ID',
  SCHEDULING_FETCHING_GET_ID: 'SCHEDULING_FETCHING_GET_ID',

  SCHEDULING_UPDATE_ID: 'SCHEDULING_UPDATE_ID',
  SCHEDULING_FETCHING_UPDATE_ID: 'SCHEDULING_FETCHING_UPDATE_ID',

  SCHEDULING_DELETE_ID: 'SCHEDULING_DELETE_ID',
  SCHEDULING_FETCHING_DELETE_ID: 'SCHEDULING_FETCHING_DELETE_ID',

  SCHEDULING_SET_SUCCESS: 'SCHEDULING_SET_SUCCESS',
  SCHEDULING_SET_FIELD_SUCCESS: 'SCHEDULING_SET_FIELD_SUCCESS',

  SCHEDULING_ERROR_MESSAGE: 'SCHEDULING_ERROR_MESSAGE',
  SCHEDULING_SUCCESS_MESSAGE: 'SCHEDULING_SUCCESS_MESSAGE',

  SCHEDULING_RESET: 'SCHEDULING_RESET',
  RESET_EDIT_STATUS: 'RESET_EDIT_STATUS',
};