export const spaceTypesConstants = {
  SPACETYPES_ADD: 'SPACETYPES_ADD',
  SPACETYPES_FETCHING_ADD: 'SPACETYPES_FETCHING_ADD',
  SPACETYPES_SUCCESS_ADDED: 'SPACETYPES_SUCCESS_ADDED',

  SPACETYPES_LIST_SPACES: 'SPACETYPES_LIST_SPACES',
  SPACETYPES_FETCHING_LIST_SPACES: 'SPACETYPES_FETCHING_LIST_SPACES',

  SPACETYPES_GET_ID: 'SPACETYPES_GET_ID',
  SPACETYPES_FETCHING_GET_ID: 'SPACETYPES_FETCHING_GET_ID',

  SPACETYPES_UPDATE_ID: 'SPACETYPES_UPDATE_ID',
  SPACETYPES_FETCHING_UPDATE_ID: 'SPACETYPES_FETCHING_UPDATE_ID',

  SPACETYPES_DELETE_ID: 'SPACETYPES_DELETE_ID',
  SPACETYPES_FETCHING_DELETE_ID: 'SPACETYPES_FETCHING_DELETE_ID',

  SPACETYPES_SET_SUCCESS: 'SPACETYPES_SET_SUCCESS',
  SPACETYPES_SET_FIELD_SUCCESS: 'SPACETYPES_SET_FIELD_SUCCESS',

  SPACETYPES_ERROR_MESSAGE: 'SPACETYPES_ERROR_MESSAGE',
  SPACETYPES_SUCCESS_MESSAGE: 'SPACETYPES_SUCCESS_MESSAGE',

  SPACETYPES_RESET: 'SPACETYPES_RESET'
};