export const userConstants = {
  SET_SEARCH: 'SET_SEARCH',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  FETCH_MESSAGE: 'FETCH_MESSAGE',

  FORGOT_REQUEST: 'USERS_FORGOT_REQUEST',
  FORGOT_SUCCESS: 'USERS_FORGOT_SUCCESS',
  FORGOT_FAILURE: 'USERS_FORGOT_FAILURE',

  PASSWORD_REQUEST: 'USERS_PASSWORD_REQUEST',
  PASSWORD_SUCCESS: 'USERS_PASSWORD_SUCCESS',
  PASSWORD_FAILURE: 'USERS_PASSWORD_FAILURE',

  SET_PASSWORD_REQUEST: 'USERS_SET_PASSWORD_REQUEST',
  SET_PASSWORD_SUCCESS: 'USERS_SET_PASSWORD_SUCCESS',
  SET_PASSWORD_FAILURE: 'USERS_SET_PASSWORD_FAILURE',

  GET_ACCESS_REQUEST: 'USERS_GET_ACCESS_REQUEST',
  GET_ACCESS_SUCCESS: 'USERS_GET_ACCESS_SUCCESS',
  GET_ACCESS_FAILURE: 'USERS_GET_ACCESS_FAILURE',

  SET_USER: 'SET_USER',

  LOGOUT: 'USERS_LOGOUT'
};