export const vehicleConstants = {
  VEHICLE_ADD: 'VEHICLE_ADD',
  VEHICLE_FETCHING_ADD: 'VEHICLE_FETCHING_ADD',
  VEHICLE_SUCCESS_ADDED: 'VEHICLE_SUCCESS_ADDED',

  VEHICLE_LIST_VEHICLES: 'VEHICLE_LIST_VEHICLES',
  VEHICLE_FETCHING_LIST_VEHICLES: 'VEHICLE_FETCHING_LIST_VEHICLES',

  VEHICLE_GET_ID: 'VEHICLE_GET_ID',
  VEHICLE_FETCHING_GET_ID: 'VEHICLE_FETCHING_GET_ID',

  VEHICLE_UPDATE_ID: 'VEHICLE_UPDATE_ID',
  VEHICLE_FETCHING_UPDATE_ID: 'VEHICLE_FETCHING_UPDATE_ID',

  VEHICLE_DELETE_ID: 'VEHICLE_DELETE_ID',
  VEHICLE_FETCHING_DELETE_ID: 'VEHICLE_FETCHING_DELETE_ID',

  VEHICLE_SET_SUCCESS: 'VEHICLE_SET_SUCCESS',
  VEHICLE_SET_FIELD_SUCCESS: 'VEHICLE_SET_FIELD_SUCCESS',

  VEHICLE_ERROR_MESSAGE: 'VEHICLE_ERROR_MESSAGE',
  VEHICLE_SUCCESS_MESSAGE: 'VEHICLE_SUCCESS_MESSAGE',

  VEHICLE_RESET: 'VEHICLE_RESET'
};