export const vehicleModelsConstants = {
  VEHICLE_MODELS_ADD: 'VEHICLE_MODELS_ADD',
  VEHICLE_MODELS_FETCHING_ADD: 'VEHICLE_MODELS_FETCHING_ADD',
  VEHICLE_MODELS_SUCCESS_ADDED: 'VEHICLE_MODELS_SUCCESS_ADDED',

  VEHICLE_MODELS_LIST_MODELS: 'VEHICLE_MODELS_LIST_MODELS',
  VEHICLE_MODELS_FETCHING_LIST_MODELS: 'VEHICLE_MODELS_FETCHING_LIST_MODELS',

  VEHICLE_MODELS_GET_ID: 'VEHICLE_MODELS_GET_ID',
  VEHICLE_MODELS_FETCHING_GET_ID: 'VEHICLE_MODELS_FETCHING_GET_ID',

  VEHICLE_MODELS_UPDATE_ID: 'VEHICLE_MODELS_UPDATE_ID',
  VEHICLE_MODELS_FETCHING_UPDATE_ID: 'VEHICLE_MODELS_FETCHING_UPDATE_ID',

  VEHICLE_MODELS_DELETE_ID: 'VEHICLE_MODELS_DELETE_ID',
  VEHICLE_MODELS_FETCHING_DELETE_ID: 'VEHICLE_MODELS_FETCHING_DELETE_ID',

  VEHICLE_MODELS_SET_SUCCESS: 'VEHICLE_MODELS_SET_SUCCESS',
  VEHICLE_MODELS_SET_FIELD_SUCCESS: 'VEHICLE_MODELS_SET_FIELD_SUCCESS',

  VEHICLE_MODELS_ERROR_MESSAGE: 'VEHICLE_MODELS_ERROR_MESSAGE',
  VEHICLE_MODELS_SUCCESS_MESSAGE: 'VEHICLE_MODELS_SUCCESS_MESSAGE',

  VEHICLE_MODELS_RESET: 'VEHICLE_MODELS_RESET'
};